apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: magento-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.appscode.com/hsts: "false"
spec:
  rules:
  - http:
      paths:
# Monolith installation
      {{/*- path: /*/}}
        {{/*backend:*/}}
          {{/*serviceName: {{ include "magento.fullname" . }}*/}}
          {{/*servicePort: {{ .Values.global.monolith.service.port }}*/}}

## Multi-service installation
      - path: /admin-ui/
        backend:
          serviceName: {{ include "magento.fullname" . }}
          servicePort: {{ .Values.global.monolith.service.port }}
      - path: /storefront/
        backend:
          serviceName: {{ include "magento.fullname" . }}-storefront
          servicePort: {{ .Values.global.monolith.service.port }}
