apiVersion: v1
kind: Service
metadata:
  name: {{ include "magento.fullname" . }}
  labels:
    app: {{ include "magento.name" . }}
    app.kubernetes.io/name: {{ include "magento.name" . }}
    helm.sh/chart: {{ include "magento.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.global.monolith.service.type }}
  ports:
    - port: {{ .Values.global.monolith.service.port }}
      targetPort: {{ .Values.global.monolith.service.nginxPort }}
  selector:
    app.kubernetes.io/name: {{ include "magento.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "magento.fullname" . }}-storefront
  labels:
    app: {{ include "magento.name" . }}
    app.kubernetes.io/name: {{ include "magento.name" . }}
    helm.sh/chart: {{ include "magento.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.global.monolith.service.type }}
  ports:
    - port: {{ .Values.global.monolith.service.port }}
      targetPort: {{ if .Values.global.caching.varnish.enabled }}{{ .Values.global.monolith.service.varnishPort }}{{ else }}{{ .Values.global.monolith.service.nginxPortStorefront }}{{ end }}
  selector:
    app.kubernetes.io/name: {{ include "magento.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: magento2-redis
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
