dependencies:
- name: mysql
  version: "8.6.3"
  appVersion: 8.0.25
  repository: "https://charts.bitnami.com/bitnami"
- name: redis
  repository: "https://charts.bitnami.com/bitnami"
  appVersion: "6.2.4"
  version: "14.6.2"
- name: rabbitmq
  repository: "https://charts.bitnami.com/bitnami"
  appVersion: "3.8.17"
  version: "8.16.0"
- name: elasticsearch
  repository: "https://charts.bitnami.com/bitnami"
  appVersion: "7.13.2"
  version: "15.6.0"
